"""Package pinned, unmodified DejaVu fonts for the Android BD-J JRE."""

import argparse
import hashlib
import io
import json
import pathlib
import struct
import tarfile
import zipfile

SOURCE_ROOT = "dejavu-fonts-ttf-2.37"
SOURCE_SHA256 = "fa9ca4d13871dd122f61258a80d01751d603b4d3ee14095d65453b4e846e17d7"
SOURCE_URL = (
    "https://github.com/dejavu-fonts/dejavu-fonts/releases/download/"
    "version_2_37/dejavu-fonts-ttf-2.37.tar.bz2"
)
STYLES = ("plain", "bold", "italic", "bolditalic")
FAMILIES = {
    "Sans": ("", "-Bold", "-Oblique", "-BoldOblique"),
    "Serif": ("", "-Bold", "-Italic", "-BoldItalic"),
    "SansMono": ("", "-Bold", "-Oblique", "-BoldOblique"),
}
LOGICAL_FAMILIES = {
    "sansserif": "Sans",
    "serif": "Serif",
    "monospaced": "SansMono",
    "dialog": "Sans",
    "dialoginput": "SansMono",
}


def font_full_names(data):
    """Read TrueType full face names without depending on a font library."""
    if data[:4] != b"\x00\x01\x00\x00":
        raise ValueError("Expected a TrueType font")
    table_count = struct.unpack_from(">H", data, 4)[0]
    for index in range(table_count):
        tag, _, offset, _ = struct.unpack_from(">4sIII", data, 12 + 16 * index)
        if tag != b"name":
            continue
        _, record_count, strings_offset = struct.unpack_from(">HHH", data, offset)
        names = set()
        for record in range(record_count):
            platform, _, _, name_id, length, start = struct.unpack_from(
                ">HHHHHH", data, offset + 6 + 12 * record
            )
            if name_id == 4 and platform in (0, 3):
                start += offset + strings_offset
                names.add(data[start:start + length].decode("utf-16-be"))
        return names
    raise ValueError("TrueType font has no name table")


def font_faces():
    faces = {}
    for family, suffixes in FAMILIES.items():
        display_family = "Sans Mono" if family == "SansMono" else family
        for style, suffix in zip(STYLES, suffixes):
            filename = "DejaVu" + family + suffix + ".ttf"
            face = "DejaVu " + display_family
            if suffix:
                face += " " + suffix[1:].replace("BoldOblique", "Bold Oblique").replace(
                    "BoldItalic", "Bold Italic"
                )
            weight = "bold" if "bold" in style else "medium"
            slant = "i" if family == "Serif" else "o"
            if "italic" not in style:
                slant = "r"
            spacing = "m" if family == "SansMono" else "p"
            xlfd = (
                f"-dejavu-dejavu {display_family.lower()}-{weight}-{slant}"
                f"-normal--0-0-0-0-{spacing}-0-iso10646-1"
            )
            faces[(family, style)] = (filename, face, xlfd)
    return faces


def font_configuration(faces):
    lines = [
        "# Generated by prepare_fonts.py; original DejaVu names and bytes are retained.",
        "version=1",
        "sequence.allfonts=default",
        "",
    ]
    for logical, family in LOGICAL_FAMILIES.items():
        for style in STYLES:
            lines.append(f"{logical}.{style}.default={faces[(family, style)][2]}")
    lines.append("")
    for filename, _, xlfd in faces.values():
        escaped_name = xlfd.replace(" ", "\\ ")
        lines.append(f"filename.{escaped_name}=$JRE_LIB_FONTS/{filename}")
    return ("\n".join(lines) + "\n").encode("ascii")


def prepare_fonts(source, output):
    if output.exists():
        raise FileExistsError(output)
    source_bytes = source.read_bytes()
    if hashlib.sha256(source_bytes).hexdigest() != SOURCE_SHA256:
        raise ValueError("Pinned DejaVu archive hash mismatch")
    faces = font_faces()
    entries = {}
    fonts = {}
    with tarfile.open(fileobj=io.BytesIO(source_bytes), mode="r:bz2") as archive:
        for filename, face, _ in faces.values():
            member = archive.getmember(f"{SOURCE_ROOT}/ttf/{filename}")
            if not member.isfile():
                raise ValueError("Expected a regular font file: " + filename)
            data = archive.extractfile(member).read()
            if face not in font_full_names(data):
                raise ValueError("Font face mismatch: " + filename)
            entries[f"jre_override/lib/fonts/{filename}"] = data
            fonts[filename] = {
                "face": face,
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        entries["jre_override/lib/fonts/DEJAVU-LICENSE.txt"] = archive.extractfile(
            f"{SOURCE_ROOT}/LICENSE"
        ).read()
    config = font_configuration(faces)
    entries["jre_override/lib/fontconfig.properties"] = config
    entries["jre_override/lib/fontconfig.Linux.properties"] = config
    font_directory = [str(len(faces))]
    font_directory.extend(f"{filename} {xlfd}" for filename, _, xlfd in faces.values())
    entries["jre_override/lib/fonts/fonts.dir"] = (
        "\n".join(font_directory) + "\n"
    ).encode("ascii")
    metadata = {
        "version": "DejaVu 2.37",
        "upstreamUrl": SOURCE_URL,
        "sourceArchiveSha256": SOURCE_SHA256,
        "licenseFile": "DEJAVU-LICENSE.txt",
        "logicalFamilies": LOGICAL_FAMILIES,
        "fonts": fonts,
    }
    entries["jre_override/lib/fonts/FONT-SOURCES.json"] = (
        json.dumps(metadata, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    entries["jre_override/FONT-SHA256SUMS"] = (
        "".join(
            f"{hashlib.sha256(data).hexdigest()}  {name.removeprefix('jre_override/')}\n"
            for name, data in sorted(entries.items())
        )
    ).encode("ascii")
    with zipfile.ZipFile(output, "x", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as target:
        for name, data in sorted(entries.items()):
            entry = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            entry.create_system = 3
            entry.external_attr = 0o100644 << 16
            target.writestr(entry, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    prepare_fonts(args.source, args.output)
    print(f"Packaged 12 original DejaVu faces: {args.output}")


if __name__ == "__main__":
    main()
